INSERT Aduana 
SELECT '19', 'TUMBES'

INSERT Aduana 
SELECT '28', 'TALARA'

INSERT Aduana 
SELECT '46', 'PAITA'

INSERT Aduana 
SELECT '55', 'CHICLAYO'

INSERT Aduana 
SELECT '82', 'SALAVERRY'

INSERT Aduana 
SELECT '91', 'CHIMBOTE'

INSERT Aduana 
SELECT '18', 'MARÍTIMA DEL CALLAO'

INSERT Aduana 
SELECT '27', 'PISCO'

INSERT Aduana 
SELECT '45', 'MOLLENDO MATARANI'

INSERT Aduana 
SELECT '54', 'AREQUIPA'

INSERT Aduana 
SELECT '63', 'ILO'

INSERT Aduana 
SELECT '72', 'TACNA'

INSERT Aduana 
SELECT '81', 'PUNO'

INSERT Aduana 
SELECT '90', 'CUZCO'

INSERT Aduana 
SELECT '17', 'PUCALLPA'

INSERT Aduana 
SELECT '26', 'IQUITOS'

INSERT Aduana 
SELECT '35', 'AÉREA DEL CALLAO'

INSERT Aduana 
SELECT '44', 'POSTAL DE LIMA'

INSERT Aduana 
SELECT '62', 'DESAGUADERO'

INSERT Aduana 
SELECT '71', 'TARAPOTO'

INSERT Aduana 
SELECT '80', 'PUERTO MALDONADO'

INSERT Aduana 
SELECT '99', 'LA TINA'

INSERT Aduana 
SELECT '84', 'DEPENDENCIA FERROVIARIA TACNA'

INSERT Aduana 
SELECT '93', 'DEPENDENCIA POSTAL TACNA'

INSERT Aduana 
SELECT '10', 'DEPENDENCIA POSTAL AREQUIPA'

