INSERT Clasificacion_Servicio 
SELECT '01', 'MERCADERIA, MATERIA PRIMA, SUMINISTRO, ENVASES Y EMBALAJES'

INSERT Clasificacion_Servicio 
SELECT '02', 'ACTIVO FIJO'

INSERT Clasificacion_Servicio 
SELECT '03', 'OTROS ACTIVOS NO CONSIDERADOS EN LOS NUMERALES 1 Y2'

INSERT Clasificacion_Servicio 
SELECT '04', 'GASTOS DE EDUCACION, RECREACION, SALUD, CULTURALES, REPRESENTACIONES'

INSERT Clasificacion_Servicio 
SELECT '05', 'OTROS GASTOS NO INCLUIDOS EN EL NUMERAL 4'

