INSERT Convenio 
SELECT '00', 'NINGUNO'

INSERT Convenio 
SELECT '01', 'CANADA'

INSERT Convenio 
SELECT '02', 'CHILE'

INSERT Convenio 
SELECT '03', 'COMUNIDAD ANDINA DE NACIONES (CAN)'

INSERT Convenio 
SELECT '04', 'BRASIL'

INSERT Convenio 
SELECT '05', 'ESTADOS UNIDOS MEXICANOS'

INSERT Convenio 
SELECT '06', 'REPUBLICA DE COREA'

INSERT Convenio 
SELECT '07', 'CONFEDERACIÓN SUIZA'

INSERT Convenio 
SELECT '08', 'PORTUGAL'

INSERT Convenio 
SELECT '09', 'OTROS'

