INSERT Modalidad_Servicio 
SELECT '01', 'SERVICIO PRESTADO INTEGRAMENTE EN EL PERÚ'

INSERT Modalidad_Servicio 
SELECT '02', 'SERVICIO PRESTADO PARTE EN EL PERÚ Y PARTE EN EL EXTRANJERO'

INSERT Modalidad_Servicio 
SELECT '03', 'SERVICIO PRESTADO EXCLUSIVAMENTE EN EL EXTRANJERO'

