INSERT Pais 
SELECT '01', 'BOUVET ISLAND'

INSERT Pais 
SELECT '02', 'COTE D’IVOIRE'

INSERT Pais 
SELECT '03', 'FALKLAND ISLANDS (MALVINAS)'

INSERT Pais 
SELECT '04', 'FRANCE, METROPOLITAN'

INSERT Pais 
SELECT '05', 'FRENCH SOUTHERN TERRITORIES'

INSERT Pais 
SELECT '06', 'HEARD AND MC DONALD ISLANDS'

INSERT Pais 
SELECT '07', 'MAYOTTE'

INSERT Pais 
SELECT '08', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS'

INSERT Pais 
SELECT '09', 'SVALBARD AND JAN MAYEN ISLANDS'

INSERT Pais 
SELECT '10', 'UNITED STATES MINOR OUTLYING ISLANDS'

INSERT Pais 
SELECT '11', 'OTROS PAISES O LUGARES'

INSERT Pais 
SELECT '13', 'AFGANISTAN'

INSERT Pais 
SELECT '17', 'ALBANIA'

INSERT Pais 
SELECT '19', 'ALDERNEY'

INSERT Pais 
SELECT '23', 'ALEMANIA'

INSERT Pais 
SELECT '26', 'ARMENIA'

INSERT Pais 
SELECT '27', 'ARUBA'

INSERT Pais 
SELECT '28', 'ASCENCI?N'

INSERT Pais 
SELECT '29', 'BOSNIA-HERZEGOVINA'

INSERT Pais 
SELECT '31', 'BURKINA FASO'

INSERT Pais 
SELECT '37', 'ANDORRA'

INSERT Pais 
SELECT '40', 'ANGOLA'

INSERT Pais 
SELECT '41', 'ANGUILLA'

INSERT Pais 
SELECT '43', 'ANTIGUA Y BARBUDA'

INSERT Pais 
SELECT '47', 'ANTILLAS HOLANDESAS'

INSERT Pais 
SELECT '53', 'ARABIA SAUDITA'

INSERT Pais 
SELECT '59', 'ARGELIA'

INSERT Pais 
SELECT '63', 'ARGENTINA'

INSERT Pais 
SELECT '69', 'AUSTRALIA'

INSERT Pais 
SELECT '72', 'AUSTRIA'

INSERT Pais 
SELECT '74', 'AZERBAIJAN'

INSERT Pais 
SELECT '77', 'BAHAMAS'

INSERT Pais 
SELECT '80', 'BAHREIN'

INSERT Pais 
SELECT '81', 'BANGLADESH'

INSERT Pais 
SELECT '83', 'BARBADOS'

INSERT Pais 
SELECT '87', 'BELGICA'

INSERT Pais 
SELECT '88', 'BELICE'

INSERT Pais 
SELECT '90', 'BERMUDAS'

INSERT Pais 
SELECT '91', 'BELARUS'

INSERT Pais 
SELECT '93', 'MYANMAR'

INSERT Pais 
SELECT '97', 'BOLIVIA'

INSERT Pais 
SELECT '01', 'BOTSWANA'

INSERT Pais 
SELECT '05', 'BRASIL'

INSERT Pais 
SELECT '08', 'BRUNEI DARUSSALAM'

INSERT Pais 
SELECT '11', 'BULGARIA'

INSERT Pais 
SELECT '15', 'BURUNDI'

INSERT Pais 
SELECT '19', 'BUTAN'

INSERT Pais 
SELECT '27', 'CABO VERDE'

INSERT Pais 
SELECT '37', 'CAIMAN,ISLAS'

INSERT Pais 
SELECT '41', 'CAMBOYA'

INSERT Pais 
SELECT '45', 'CAMERUN,REPUBLICA UNIDA DEL'

INSERT Pais 
SELECT '47', 'CAMPIONE D?TALIA'

INSERT Pais 
SELECT '49', 'CANADA'

INSERT Pais 
SELECT '55', 'CANAL (NORMANDAS), ISLAS'

INSERT Pais 
SELECT '57', 'CANTON Y ENDERBURRY'

INSERT Pais 
SELECT '59', 'SANTA SEDE'

INSERT Pais 
SELECT '65', 'COCOS (KEELING),ISLAS'

INSERT Pais 
SELECT '69', 'COLOMBIA'

INSERT Pais 
SELECT '73', 'COMORAS'

INSERT Pais 
SELECT '77', 'CONGO'

INSERT Pais 
SELECT '83', 'COOK, ISLAS'

INSERT Pais 
SELECT '87', 'COREA (NORTE), REPUBLICA POPULAR DEMOCRATICA DE'

INSERT Pais 
SELECT '90', 'COREA (SUR), REPUBLICA DE'

INSERT Pais 
SELECT '93', 'COSTA DE MARFIL'

INSERT Pais 
SELECT '96', 'COSTA RICA'

INSERT Pais 
SELECT '98', 'CROACIA'

INSERT Pais 
SELECT '99', 'CUBA'

INSERT Pais 
SELECT '03', 'CHAD'

INSERT Pais 
SELECT '07', 'CHECOSLOVAQUIA'

INSERT Pais 
SELECT '11', 'CHILE'

INSERT Pais 
SELECT '15', 'CHINA'

INSERT Pais 
SELECT '18', 'TAIWAN (FORMOSA)'

INSERT Pais 
SELECT '21', 'CHIPRE'

INSERT Pais 
SELECT '29', 'BENIN'

INSERT Pais 
SELECT '32', 'DINAMARCA'

INSERT Pais 
SELECT '35', 'DOMINICA'

INSERT Pais 
SELECT '39', 'ECUADOR'

INSERT Pais 
SELECT '40', 'EGIPTO'

INSERT Pais 
SELECT '42', 'EL SALVADOR'

INSERT Pais 
SELECT '43', 'ERITREA'

INSERT Pais 
SELECT '44', 'EMIRATOS ARABES UNIDOS'

INSERT Pais 
SELECT '45', 'ESPA?A'

INSERT Pais 
SELECT '46', 'ESLOVAQUIA'

INSERT Pais 
SELECT '47', 'ESLOVENIA'

INSERT Pais 
SELECT '49', 'ESTADOS UNIDOS'

INSERT Pais 
SELECT '51', 'ESTONIA'

INSERT Pais 
SELECT '53', 'ETIOPIA'

INSERT Pais 
SELECT '59', 'FEROE, ISLAS'

INSERT Pais 
SELECT '67', 'FILIPINAS'

INSERT Pais 
SELECT '71', 'FINLANDIA'

INSERT Pais 
SELECT '75', 'FRANCIA'

INSERT Pais 
SELECT '81', 'GABON'

INSERT Pais 
SELECT '85', 'GAMBIA'

INSERT Pais 
SELECT '86', 'GAZA Y JERICO'

INSERT Pais 
SELECT '87', 'GEORGIA'

INSERT Pais 
SELECT '89', 'GHANA'

INSERT Pais 
SELECT '93', 'GIBRALTAR'

INSERT Pais 
SELECT '97', 'GRANADA'

INSERT Pais 
SELECT '01', 'GRECIA'

INSERT Pais 
SELECT '05', 'GROENLANDIA'

INSERT Pais 
SELECT '09', 'GUADALUPE'

INSERT Pais 
SELECT '13', 'GUAM'

INSERT Pais 
SELECT '17', 'GUATEMALA'

INSERT Pais 
SELECT '25', 'GUAYANA FRANCESA'

INSERT Pais 
SELECT '27', 'GUERNSEY'

INSERT Pais 
SELECT '29', 'GUINEA'

INSERT Pais 
SELECT '31', 'GUINEA ECUATORIAL'

INSERT Pais 
SELECT '34', 'GUINEA-BISSAU'

INSERT Pais 
SELECT '37', 'GUYANA'

INSERT Pais 
SELECT '41', 'HAITI'

INSERT Pais 
SELECT '45', 'HONDURAS'

INSERT Pais 
SELECT '48', 'HONDURAS BRITANICAS'

INSERT Pais 
SELECT '51', 'HONG KONG'

INSERT Pais 
SELECT '55', 'HUNGRIA'

INSERT Pais 
SELECT '61', 'INDIA'

INSERT Pais 
SELECT '65', 'INDONESIA'

INSERT Pais 
SELECT '69', 'IRAK'

INSERT Pais 
SELECT '72', 'IRAN, REPUBLICA ISLAMICA DEL'

INSERT Pais 
SELECT '75', 'IRLANDA (EIRE)'

INSERT Pais 
SELECT '77', 'ISLA AZORES'

INSERT Pais 
SELECT '78', 'ISLA DEL MAN'

INSERT Pais 
SELECT '79', 'ISLANDIA'

INSERT Pais 
SELECT '80', 'ISLAS CANARIAS'

INSERT Pais 
SELECT '81', 'ISLAS DE CHRISTMAS'

INSERT Pais 
SELECT '82', 'ISLAS QESHM'

INSERT Pais 
SELECT '83', 'ISRAEL'

INSERT Pais 
SELECT '86', 'ITALIA'

INSERT Pais 
SELECT '91', 'JAMAICA'

INSERT Pais 
SELECT '95', 'JONSTON, ISLAS'

INSERT Pais 
SELECT '99', 'JAPON'

INSERT Pais 
SELECT '01', 'JERSEY'

INSERT Pais 
SELECT '03', 'JORDANIA'

INSERT Pais 
SELECT '06', 'KAZAJSTAN'

INSERT Pais 
SELECT '10', 'KENIA'

INSERT Pais 
SELECT '11', 'KIRIBATI'

INSERT Pais 
SELECT '12', 'KIRGUIZISTAN'

INSERT Pais 
SELECT '13', 'KUWAIT'

INSERT Pais 
SELECT '18', 'LABUN'

INSERT Pais 
SELECT '20', 'LAOS, REPUBLICA POPULAR DEMOCRATICA DE'

INSERT Pais 
SELECT '26', 'LESOTHO'

INSERT Pais 
SELECT '29', 'LETONIA'

INSERT Pais 
SELECT '31', 'LIBANO'

INSERT Pais 
SELECT '34', 'LIBERIA'

INSERT Pais 
SELECT '38', 'LIBIA'

INSERT Pais 
SELECT '40', 'LIECHTENSTEIN'

INSERT Pais 
SELECT '43', 'LITUANIA'

INSERT Pais 
SELECT '45', 'LUXEMBURGO'

INSERT Pais 
SELECT '47', 'MACAO'

INSERT Pais 
SELECT '48', 'MACEDONIA'

INSERT Pais 
SELECT '50', 'MADAGASCAR'

INSERT Pais 
SELECT '53', 'MADEIRA'

INSERT Pais 
SELECT '55', 'MALAYSIA'

INSERT Pais 
SELECT '58', 'MALAWI'

INSERT Pais 
SELECT '61', 'MALDIVAS'

INSERT Pais 
SELECT '64', 'MALI'

INSERT Pais 
SELECT '67', 'MALTA'

INSERT Pais 
SELECT '69', 'MARIANAS DEL NORTE, ISLAS'

INSERT Pais 
SELECT '72', 'MARSHALL, ISLAS'

INSERT Pais 
SELECT '74', 'MARRUECOS'

INSERT Pais 
SELECT '77', 'MARTINICA'

INSERT Pais 
SELECT '85', 'MAURICIO'

INSERT Pais 
SELECT '88', 'MAURITANIA'

INSERT Pais 
SELECT '93', 'MEXICO'

INSERT Pais 
SELECT '94', 'MICRONESIA, ESTADOS FEDERADOS DE'

INSERT Pais 
SELECT '95', 'MIDWAY ISLAS'

INSERT Pais 
SELECT '96', 'MOLDAVIA'

INSERT Pais 
SELECT '97', 'MONGOLIA'

INSERT Pais 
SELECT '98', 'MONACO'

INSERT Pais 
SELECT '01', 'MONTSERRAT, ISLA'

INSERT Pais 
SELECT '05', 'MOZAMBIQUE'

INSERT Pais 
SELECT '07', 'NAMIBIA'

INSERT Pais 
SELECT '08', 'NAURU'

INSERT Pais 
SELECT '11', 'NAVIDAD (CHRISTMAS), ISLA'

INSERT Pais 
SELECT '17', 'NEPAL'

INSERT Pais 
SELECT '21', 'NICARAGUA'

INSERT Pais 
SELECT '25', 'NIGER'

INSERT Pais 
SELECT '28', 'NIGERIA'

INSERT Pais 
SELECT '31', 'NIUE, ISLA'

INSERT Pais 
SELECT '35', 'NORFOLK, ISLA'

INSERT Pais 
SELECT '38', 'NORUEGA'

INSERT Pais 
SELECT '42', 'NUEVA CALEDONIA'

INSERT Pais 
SELECT '45', 'PAPUASIA NUEVA GUINEA'

INSERT Pais 
SELECT '48', 'NUEVA ZELANDA'

INSERT Pais 
SELECT '51', 'VANUATU'

INSERT Pais 
SELECT '56', 'OMAN'

INSERT Pais 
SELECT '66', 'PACIFICO, ISLAS DEL'

INSERT Pais 
SELECT '73', 'PAISES BAJOS'

INSERT Pais 
SELECT '76', 'PAKISTAN'

INSERT Pais 
SELECT '78', 'PALAU, ISLAS'

INSERT Pais 
SELECT '79', 'TERRITORIO AUTONOMO DE PALESTINA.'

INSERT Pais 
SELECT '80', 'PANAMA'

INSERT Pais 
SELECT '86', 'PARAGUAY'

INSERT Pais 
SELECT '89', 'PERU'

INSERT Pais 
SELECT '93', 'PITCAIRN, ISLA'

INSERT Pais 
SELECT '99', 'POLINESIA FRANCESA'

INSERT Pais 
SELECT '03', 'POLONIA'

INSERT Pais 
SELECT '07', 'PORTUGAL'

INSERT Pais 
SELECT '11', 'PUERTO RICO'

INSERT Pais 
SELECT '18', 'QATAR'

INSERT Pais 
SELECT '28', 'REINO UNIDO'

INSERT Pais 
SELECT '29', 'ESCOCIA'

INSERT Pais 
SELECT '33', 'REPUBLICA ARABE UNIDA'

INSERT Pais 
SELECT '40', 'REPUBLICA CENTROAFRICANA'

INSERT Pais 
SELECT '44', 'REPUBLICA CHECA'

INSERT Pais 
SELECT '45', 'REPUBLICA DE SWAZILANDIA'

INSERT Pais 
SELECT '46', 'REPUBLICA DE TUNEZ'

INSERT Pais 
SELECT '47', 'REPUBLICA DOMINICANA'

INSERT Pais 
SELECT '60', 'REUNION'

INSERT Pais 
SELECT '65', 'ZIMBABWE'

INSERT Pais 
SELECT '70', 'RUMANIA'

INSERT Pais 
SELECT '75', 'RUANDA'

INSERT Pais 
SELECT '76', 'RUSIA'

INSERT Pais 
SELECT '77', 'SALOMON, ISLAS'

INSERT Pais 
SELECT '85', 'SAHARA OCCIDENTAL'

INSERT Pais 
SELECT '87', 'SAMOA OCCIDENTAL'

INSERT Pais 
SELECT '90', 'SAMOA NORTEAMERICANA'

INSERT Pais 
SELECT '95', 'SAN CRISTOBAL Y NIEVES'

INSERT Pais 
SELECT '97', 'SAN MARINO'

INSERT Pais 
SELECT '00', 'SAN PEDRO Y MIQUELON'

INSERT Pais 
SELECT '05', 'SAN VICENTE Y LAS GRANADINAS'

INSERT Pais 
SELECT '10', 'SANTA ELENA'

INSERT Pais 
SELECT '15', 'SANTA LUCIA'

INSERT Pais 
SELECT '20', 'SANTO TOME Y PRINCIPE'

INSERT Pais 
SELECT '28', 'SENEGAL'

INSERT Pais 
SELECT '31', 'SEYCHELLES'

INSERT Pais 
SELECT '35', 'SIERRA LEONA'

INSERT Pais 
SELECT '41', 'SINGAPUR'

INSERT Pais 
SELECT '44', 'SIRIA, REPUBLICA ARABE DE'

INSERT Pais 
SELECT '48', 'SOMALIA'

INSERT Pais 
SELECT '50', 'SRI LANKA'

INSERT Pais 
SELECT '56', 'SUDAFRICA, REPUBLICA DE'

INSERT Pais 
SELECT '59', 'SUDAN'

INSERT Pais 
SELECT '64', 'SUECIA'

INSERT Pais 
SELECT '67', 'SUIZA'

INSERT Pais 
SELECT '70', 'SURINAM'

INSERT Pais 
SELECT '73', 'SAWSILANDIA'

INSERT Pais 
SELECT '74', 'TADJIKISTAN'

INSERT Pais 
SELECT '76', 'TAILANDIA'

INSERT Pais 
SELECT '80', 'TANZANIA, REPUBLICA UNIDA DE'

INSERT Pais 
SELECT '83', 'DJIBOUTI'

INSERT Pais 
SELECT '86', 'TERRITORIO ANTARTICO BRITANICO'

INSERT Pais 
SELECT '87', 'TERRITORIO BRITANICO DEL OCEANO INDICO'

INSERT Pais 
SELECT '88', 'TIMOR DEL ESTE'

INSERT Pais 
SELECT '00', 'TOGO'

INSERT Pais 
SELECT '05', 'TOKELAU'

INSERT Pais 
SELECT '10', 'TONGA'

INSERT Pais 
SELECT '15', 'TRINIDAD Y TOBAGO'

INSERT Pais 
SELECT '16', 'TRISTAN DA CUNHA'

INSERT Pais 
SELECT '20', 'TUNICIA'

INSERT Pais 
SELECT '23', 'TURCAS Y CAICOS, ISLAS'

INSERT Pais 
SELECT '25', 'TURKMENISTAN'

INSERT Pais 
SELECT '27', 'TURQUIA'

INSERT Pais 
SELECT '28', 'TUVALU'

INSERT Pais 
SELECT '30', 'UCRANIA'

INSERT Pais 
SELECT '33', 'UGANDA'

INSERT Pais 
SELECT '40', 'URSS'

INSERT Pais 
SELECT '45', 'URUGUAY'

INSERT Pais 
SELECT '47', 'UZBEKISTAN'

INSERT Pais 
SELECT '50', 'VENEZUELA'

INSERT Pais 
SELECT '55', 'VIET NAM'

INSERT Pais 
SELECT '58', 'VIETNAM (DEL NORTE)'

INSERT Pais 
SELECT '63', 'VIRGENES, ISLAS (BRITANICAS)'

INSERT Pais 
SELECT '66', 'VIRGENES, ISLAS (NORTEAMERICANAS)'

INSERT Pais 
SELECT '70', 'FIJI'

INSERT Pais 
SELECT '73', 'WAKE, ISLA'

INSERT Pais 
SELECT '75', 'WALLIS Y FORTUNA, ISLAS'

INSERT Pais 
SELECT '80', 'YEMEN'

INSERT Pais 
SELECT '85', 'YUGOSLAVIA'

INSERT Pais 
SELECT '88', 'ZAIRE'

INSERT Pais 
SELECT '90', 'ZAMBIA'

INSERT Pais 
SELECT '95', 'ZONA DEL CANAL DE PANAMA'

INSERT Pais 
SELECT '96', 'ZONA LIBRE OSTRAVA'

INSERT Pais 
SELECT '97', 'ZONA NEUTRAL (PALESTINA)'

