ALTER TABLE dbo.CNC_ASIENTO_VOUCHER
ADD CreditoFiscal CHAR(1)
GO

ALTER TABLE dbo.CNC_ASIENTO_VOUCHER
ADD MaterialConstruccion CHAR(1)
GO

ALTER TABLE dbo.CNM_ENTIDAD
ADD PorcentajeSunat CHAR(1)
GO