name: Build

on:
  workflow_dispatch:

  push:
    branches: [ "main", "develop", "feature/**", "fix/**", "refactor/**" ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - run: echo "build.txt" | Out-File -FilePath "build.txt"
    - run: while (!(Test-Path("compile.log")) { Start-Sleep -Seconds 5}
      timeout-minutes: 20

    - run: Get-Content "compile.log"
    - run: if (!(Test-path "ECB-Cont.exe")) { Write-Error "Workflow failed, check the VB6 compile.log file"; exit 1 }
    - run: if ((Test-path "C:\Runners\ECB_Cont\_work\ecb_cont\")) { Get-ChildItem "C:\Runners\ECB_Cont\_work\ecb_cont\" | Remove-Item -Recurse -Force }

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: vb6-executable
        path: ECB-Cont.exe

        
